import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Next with Cloudinary</h1>

        <img
          src="https://res.cloudinary.com/literallymarvellous/image/upload/v1672033694/860E15B5-FE48-4EE4-8815-D2002F59DD4C_jr4nzh.jpg"
          alt="myself"
        />
      </main>
    </>
  );
}
